{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The primary classes you’ll use when retrieving health metrics are the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity"},{"type":"text","text":" classes."}]},{"anchor":"Understanding-Sources-Manual-Sources-Tile-Settings-and-Metrics","level":3,"type":"heading","text":"Understanding Sources, Manual Sources, Tile Settings and Metrics"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When retrieving Health Metric Data it’s important to understand the relationship between Sources, Manual Sources, Tile Settings, and Metrics."}]},{"anchor":"Sources","level":4,"type":"heading","text":"Sources"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Sources represent all of the health metrics that are available in the Heads Up platform. This includes metrics such as blood pressure, heart rate, calories burned, calories consumed, blood glucose, and so on."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController"},{"type":"text","text":" can retrieve the full list of available health metric sources. You call its "},{"type":"strong","inlineContent":[{"type":"text","text":"getSources()"}]},{"type":"text","text":" method to retrieve the list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity"},{"type":"text","text":" objects."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["SourceController.shared.getSources { ","    sourcesList in","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity"},{"type":"text","text":" object in the list contains the following properties:"}]},{"type":"codeListing","syntax":"swift","code":["public class SourceEntity: Decodable {","    \/\/\/  Source url","    public var url: String","    \/\/\/ Source metric grouping (i.e. Metabolism, Vitals, Cardiovascular, etc)","    public var group: String","    \/\/\/ Display name","    public var name: String","    \/\/\/ A list of devices associated with the source (i.e. Apple Health, Dexcom, Oura, Manual entry)","    public var supported_devices: [SelectableItem]","    \/\/\/ True if the current user has a tile on their dashboard for this source","    public var existed_tile: Bool","    \/\/\/ The name of the dashboard tile icon associated with this source","    public var icon: String?","}"]},{"anchor":"Manual-Sources","level":4,"type":"heading","text":"Manual Sources"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Manual sources represent all of the health metrics in the Heads Up platform that can optionally be entered manually by the user. This includes metrics that are not normally added by means of Apple Health or one of the many supported devices."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController"},{"type":"text","text":" can retrieve the full list of manual sources. You call its "},{"type":"strong","inlineContent":[{"type":"text","text":"getManualSources()"}]},{"type":"text","text":" method to retrieve the list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity"},{"type":"text","text":" objects."}]},{"type":"codeListing","syntax":"swift","code":["ManualSourceController.shared.getManualSources { ","    entityList, errorMessage in","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity"},{"type":"text","text":" object in the list contains the following properties. Note the "},{"type":"strong","inlineContent":[{"type":"text","text":"fields"}]},{"type":"text","text":" property which allows you to dynamically build a UI for manual data entry:"}]},{"type":"codeListing","syntax":"swift","code":["public class ManualSourceEntity: Decodable {","    \/\/\/ Source display name","    public var name: String","    \/\/\/ source url","    public var url: String","    \/\/\/ Group the source belongs to (e.g. Vitals, Symptoms, Lifestyle)","    public var group: String","    \/\/\/ If true, this is a source metric, otherwise false","    public var sourceMetricDefinition: Bool?","    \/\/\/ Field definitions used to build manual entry UI","    public var fields: [ManualSourceField]?","}"]},{"anchor":"Tile-Settings","level":4,"type":"heading","text":"Tile Settings"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tile Settings specify the tiles that a user has on their mobile dashboard. The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController"},{"type":"text","text":" can retrieve the list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity"},{"type":"text","text":" objects that represent the tiles on a user’s mobile dashboard."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["\/\/ Get all user tile data","TileSettingController.shared.getTilesSettings { ","    tileSettingList, errorMessage in","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity"},{"type":"text","text":" object in the list contains the following properties:"}]},{"type":"codeListing","syntax":"swift","code":["public class TileSettingEntity: Decodable {","    \/\/\/ Unique Tile ID","    public var id: Int","    \/\/\/ The url of the tile's source","    public var url: String","    \/\/\/ The display position","    public var position: Int","    \/\/\/ The user's goal for this source (e.g. \"2500\" burned calories)","    public var goal: String? = nil","    \/\/\/ The color associated with the tile","    public var color: String","    \/\/\/ The device currently associated with the tile source (e.g. healthkit2, oura, manual)","    public var defaultDevice: String","    \/\/\/ The display name of the default device (e.g. Apple Health, Oura, Manual)","    public var deviceLabel: String","    \/\/\/ The display name of the source (e.g. Heart Rate, Weight, Steps)","    public var name: String","    \/\/\/ Display type","    public var displayType: TileSettingDisplayType","    \/\/\/ The latest data associated with the source for display on a dashboard tile","    public var data: MetricEntity?","    \/\/\/ The icon associated with this tile","    public var icon: String?","    \/\/\/ If true, this tile has an option for a 24 hour graph, otherwise false","    public var has24HourGraphOption: Bool?","}"]},{"anchor":"Metrics","level":4,"type":"heading","text":"Metrics"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Metrics are the individual values recorded for each source being tracked by the user. The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController"},{"type":"text","text":" can retrieve a list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity"},{"type":"text","text":" objects for a given metric, source, device and date range. There are two methods that return metrics. Depending on the metric you are retrieving, you call one method or the other."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity"},{"type":"text","text":" associated with the metric has its "},{"type":"strong","inlineContent":[{"type":"text","text":"sourceMetricDefinition"}]},{"type":"text","text":" property set to true, you call the MetricController’s "},{"type":"strong","inlineContent":[{"type":"text","text":"getMetricDictionaryByCalendarRange()"}]},{"type":"text","text":" method:"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["MetricController.shared.getMetricDictionaryByCalendarRange(url: \"steps\", ","    device: \"healthkit2\", ","    calendarRange: .year, ","    currentDate: Date(), ","    scale: \"raw\") { ","        entityList, errorMessage in","","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity"},{"type":"text","text":" associated with the metric has its "},{"type":"strong","inlineContent":[{"type":"text","text":"sourceMetricDefinition"}]},{"type":"text","text":" property set to false, you call the MetricController’s "},{"type":"strong","inlineContent":[{"type":"text","text":"getMetricByCalendarRange()"}]},{"type":"text","text":" method:"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["MetricController.shared.getMetricByCalendarRange(url: \"heart_rate\", ","    device: \"healthkit2\", ","    calendarRange: .year, ","    currentDate: Date(), ","    scale: \"raw\") { ","        entityList, errorMessage in","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"There is a wealth of data available in the Heads Up platform you can retrieve and manipulate from the Heads Up SDK. This article shows the objects you can use to download this data into your own app."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Retrieving Health Metric Data","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit"],"generated":true}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceEntity":{"role":"symbol","title":"ManualSourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceEntity"}],"abstract":[{"type":"text","text":"Manual Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithUserData":{"role":"article","title":"Working With User Data","abstract":[{"type":"text","text":"Most of the functionality in the Heads Up Mobile SDK requires access to a user’s data. This topic discusses how to retrieve and update user data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithuserdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegistrationLogin":{"role":"article","title":"Registration, Login and Logout","abstract":[{"type":"text","text":"The first step in using the Heads Up Mobile SDK’s features is to register and-or log in a user."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registrationlogin"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingEntity":{"role":"symbol","title":"TileSettingEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingEntity"}],"abstract":[{"type":"text","text":"Tile Setting Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceController":{"role":"symbol","title":"ManualSourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceController"}],"abstract":[{"type":"text","text":"Manual Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingController":{"role":"symbol","title":"TileSettingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingController"}],"abstract":[{"type":"text","text":"Tile Setting Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingController"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingSDK":{"role":"article","title":"Installing the Heads Up SDK","abstract":[{"type":"text","text":"This topic contains instructions for installing the Heads Up Mobile SDK and integrating it into your mobile project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingsdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithAppleHealthKit":{"role":"article","title":"Working With Apple HealthKit","abstract":[{"type":"text","text":"Apple’s HealthKit provides a vast array of health information that is accessible through the Heads Up SDK. In this article you’ll learn about the Heads Up SDK objects you can work with to upload and manipulate HealthKit data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController":{"role":"symbol","title":"MetricController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricController"}],"abstract":[{"type":"text","text":"Metric Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricController"}],"url":"\/documentation\/headsup_mobile_sdk\/metriccontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricEntity":{"role":"symbol","title":"MetricEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricEntity"}],"abstract":[{"type":"text","text":"Metric Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/metricentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceController":{"role":"symbol","title":"SourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceController"}],"abstract":[{"type":"text","text":"Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/sourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ArchitecturalOverview":{"role":"article","title":"Architectural Overview","abstract":[{"type":"text","text":"This article provides an architectural overview of how your app interacts with the Heads Up Mobile SDK to access the functionality of the Heads Up Cloud Platform."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/architecturaloverview"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSources":{"role":"article","title":"Connecting and Disconnecting Sources","abstract":[{"type":"text","text":"The Heads Up platform integrates with many popular apps and data sources such as Apple Health, Oura, Dexcom and Fitbit. In this article, you’ll learn how to connect and disconnect these various sources."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsources"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity":{"role":"symbol","title":"SourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceEntity"}],"abstract":[{"type":"text","text":"Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/sourceentity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/title","value":"MetricEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/fragments","value":[{"kind":"identifier","text":"MetricEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}