{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The primary class you’ll use when working with Apple HealthKit is the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit"},{"type":"text","text":" class."}]},{"anchor":"Initializing-HealthKit","level":3,"type":"heading","text":"Initializing HealthKit"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When your mobile app first starts up, if the user has connect Apple Health as a data source, you need to call the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit"},{"type":"text","text":" object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"initHealthKit()"}]},{"type":"text","text":" method. The following code first calls HealthKit’s "},{"type":"strong","inlineContent":[{"type":"text","text":"isHealthKitConnected()"}]},{"type":"text","text":" method to determine if the user has connected HealthKit as a data source. If so, it grabs the user’s credentials from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HUHClient"},{"type":"text","text":" object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"getAuthDictionary()"}]},{"type":"text","text":" method then calls the HealthKit object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"initHealthKit()"}]},{"type":"text","text":" method. Afterwards, it calls the HealthKit object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"setObservers()"}]},{"type":"text","text":" method. See the next section for details."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["HealthKit.shared.isHealthKitConnectedOnServer { isConnected in","    if isConnected {","        let dictionary = HUHClient.instance.getAuthDictionary()","        \/\/ Initialize HealthKit","        HealthKit.shared.initHealthKit(input: dictionary) { success in","            \/\/ Set background observers for HealthKit","            if success {","                HealthKit.shared.setObservers(input: dictionary) { success in","                }","            }","        }","    }","}"]},{"anchor":"Connecting-and-Disconnecting-Apple-Health-as-a-Source","level":3,"type":"heading","text":"Connecting and Disconnecting Apple Health as a Source"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For information on Connecting and Disconnecting as a source, please check out the topic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesAppleHealth"},{"type":"text","text":"."}]},{"anchor":"HealthKit-Background-Observers","level":3,"type":"heading","text":"HealthKit Background Observers"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you call the HealthKit object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"setObservers()"}]},{"type":"text","text":" method, it creates background observers that automatically upload HealthKit data to the Heads Up cloud in the background. This works even when the user has force-closed your mobile app. When new HealthKit data is added (for example, additional steps from the Apple Watch), this new data is automatically uploaded. This means that you normally don’t need to call the HealthKit object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"uploadHealthKitData()"}]},{"type":"text","text":" method unless the user has just connected Apple Health as a source."}]},{"anchor":"Understanding-Anchors","level":3,"type":"heading","text":"Understanding Anchors"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To keep track of which HealthKit data has been uploaded to the Heads Up Cloud, the HealthKit object creates an “anchor” object after each successful upload. A separate anchor is created for each HealthKit metric."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the rare situation arises where you need the user to reupload all of their HealthKit data, you can call the HealthKit object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"clearAnchor()"}]},{"type":"text","text":" method, which clears all anchors and causes all of a user’s HealthKit data to be re-uploaded."}]},{"anchor":"Determining-if-HealthKit-is-Available","level":3,"type":"heading","text":"Determining if HealthKit is Available"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since HealthKit is not available on all iOS devices (it’s unavailable on the iPad before iOS17) you can call the HealthKit object’s "},{"type":"strong","inlineContent":[{"type":"text","text":"isAvailable()"}]},{"type":"text","text":" method to see if HealthKit is available."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Apple’s HealthKit provides a vast array of health information that is accessible through the Heads Up SDK. In this article you’ll learn about the Heads Up SDK objects you can work with to upload and manipulate HealthKit data."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Working With Apple HealthKit","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HUHClient":{"role":"symbol","title":"HUHClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUHClient"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HUHClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HUHClient"}],"url":"\/documentation\/headsup_mobile_sdk\/huhclient"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RetrievingHealthData":{"role":"article","title":"Retrieving Health Metric Data","abstract":[{"type":"text","text":"There is a wealth of data available in the Heads Up platform you can retrieve and manipulate from the Heads Up SDK. This article shows the objects you can use to download this data into your own app."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSources":{"role":"article","title":"Connecting and Disconnecting Sources","abstract":[{"type":"text","text":"The Heads Up platform integrates with many popular apps and data sources such as Apple Health, Oura, Dexcom and Fitbit. In this article, you’ll learn how to connect and disconnect these various sources."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsources"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingSDK":{"role":"article","title":"Installing the Heads Up SDK","abstract":[{"type":"text","text":"This topic contains instructions for installing the Heads Up Mobile SDK and integrating it into your mobile project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingsdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegistrationLogin":{"role":"article","title":"Registration, Login and Logout","abstract":[{"type":"text","text":"After installing the Heads Up SDK, the next step in using the SDK’s features is to register and-or log in a user."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registrationlogin"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithUserData":{"role":"article","title":"Working With User Data","abstract":[{"type":"text","text":"Most of the functionality in the Heads Up Mobile SDK requires access to a user’s data. This topic discusses how to retrieve and update user data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithuserdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSourcesAppleHealth":{"role":"article","title":"Connecting and Disconnecting Apple Health","abstract":[{"type":"text","text":"This topic shows you how to connect and disconnect Apple Health."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesAppleHealth","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsourcesapplehealth"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit":{"role":"symbol","title":"HealthKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"}],"abstract":[{"type":"text","text":"The primary HealthKit class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HealthKit"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ArchitecturalOverview":{"role":"article","title":"Architectural Overview","abstract":[{"type":"text","text":"This article provides an architectural overview of how your app interacts with the Heads Up Mobile SDK to access the functionality of the Heads Up Cloud Platform."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/architecturaloverview"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HUHClient\/title","value":"HUHClient"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HUHClient\/fragments","value":[{"kind":"identifier","text":"HUHClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/title","value":"HealthKit"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/fragments","value":[{"kind":"identifier","text":"HealthKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}